---
- name: Install Java, Docker, Jenkins (reference install)
  hosts: localhost          # or your Azure host/group
  become: yes

  vars_files:
    - vars/main.yml

  tasks:
    - import_tasks: tasks/main.yml
